"""Jinja2 HTML settlement letter for a reconciled voyage."""

from __future__ import annotations

from datetime import date
from jinja2 import Environment, select_autoescape

# Every value reaching this template is LLM output extracted from user-uploaded
# PDFs, and the frontend injects the result with dangerouslySetInnerHTML, so the
# template must escape by default. `default_for_string=True` is required: these
# templates come from strings, and select_autoescape() returns False for those
# otherwise. Only literal template markup is emitted unescaped; every {{ ... }}
# expression below holds text or a number, never intentional HTML.
_ENV = Environment(autoescape=select_autoescape(default=True, default_for_string=True))

_TEMPLATE_SOURCE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Demurrage Reconciliation Notice – {{ voyage_id }}</title>
<style>
  body { margin: 0; padding: 0; }
  .letter-container { font-family: Georgia, serif; max-width: 1200px; margin: 40px auto; color: #1a1a1a; }
  .letter-container h1 { font-size: 1.4rem; text-transform: uppercase; letter-spacing: .08em; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; }
  .letter-container h2 { font-size: 1rem; text-transform: uppercase; letter-spacing: .06em; margin-top: 2rem; }
  .letter-container table { width: 100%; border-collapse: collapse; margin-top: .5rem; }
  .letter-container th { text-align: left; font-size: .8rem; text-transform: uppercase; color: #555; border-bottom: 1px solid #ccc; padding: 4px 8px; }
  .letter-container td { padding: 6px 8px; vertical-align: top; }
  .letter-container tr:nth-child(even) td { background: #f9f9f9; }
  .letter-container .verdict-owner { color: #1a5276; font-weight: bold; }
  .letter-container .verdict-charterer { color: #78281f; font-weight: bold; }
  .letter-container .totals { margin-top: 2rem; border-top: 2px solid #1a1a1a; padding-top: 1rem; }
  .letter-container .totals table td:first-child { font-weight: bold; width: 40%; }
  .letter-container .reconciled { font-size: 1.3rem; font-weight: bold; }
  .letter-container .footer { margin-top: 3rem; font-size: .8rem; color: #777; border-top: 1px solid #ccc; padding-top: .5rem; }
</style>
</head>
<body>
<div class="letter-container">

<h1>Demurrage Reconciliation Notice</h1>

<table>
  <tr><th>Voyage ID</th><td>{{ voyage_id }}</td></tr>
  <tr><th>Vessel</th><td>{{ charterparty.vessel_name }}</td></tr>
  <tr><th>Laytime allowed</th><td>{{ charterparty.laytime_allowed_hours }} hours</td></tr>
  <tr><th>Demurrage rate</th><td>${{ "{:,.0f}".format(charterparty.demurrage_rate_per_day_usd) }}/day</td></tr>
  <tr><th>Date of issue</th><td>{{ issue_date }}</td></tr>
</table>

<h2>Party Positions</h2>
<table>
  <tr>
    <th>Party</th>
    <th>Claimed Amount</th>
  </tr>
  <tr>
    <td>Owner</td>
    <td>${{ "{:,.0f}".format(owner_calculation.total_usd) }}</td>
  </tr>
  <tr>
    <td>Charterer</td>
    <td>${{ "{:,.0f}".format(charterer_calculation.total_usd) }}</td>
  </tr>
</table>

<h2>Day-by-Day Assessment</h2>
<table>
  <tr>
    <th>Date</th>
    <th>Owner Position</th>
    <th>Charterer Position</th>
    <th>Assessment</th>
    <th>Credited (USD)</th>
  </tr>
  {% for v in day_verdicts %}
  <tr>
    <td>{{ v.date }}</td>
    <td>{{ v.owner_position }}</td>
    <td>{{ v.charterer_position }}</td>
    <td class="verdict-{{ v.verdict }}">{{ v.winner_label }}</td>
    <td>${{ "{:,.0f}".format(v.dollars_credited_usd) }}</td>
  </tr>
  {% endfor %}
</table>

{% if day_verdicts %}
<p><em>Justification (final disputed day): {{ day_verdicts[-1].justification }}</em></p>
{% endif %}

<div class="totals">
  <h2>Reconciled Settlement</h2>
  <table>
    <tr><td>Charterer base liability</td><td>${{ "{:,.0f}".format(charterer_calculation.total_usd) }}</td></tr>
    <tr><td>Items favouring the owner&rsquo;s position</td><td>${{ "{:,.0f}".format(reconciled_total_usd - charterer_calculation.total_usd) }}</td></tr>
    <tr><td class="reconciled">Reconciled Total</td><td class="reconciled">${{ "{:,.0f}".format(reconciled_total_usd) }}</td></tr>
  </table>
  <p>{{ math_breakdown }}</p>
</div>

<div class="footer">
  <p>Generated by Keel &middot; excepted periods are measured on the basis given by
  definition 16 of the Laytime Definitions for Charter Parties 2013 (BIMCO Special
  Circular No. 8). That document supplies the measurement basis only: it states no
  Force 6 and no majority test. The weather thresholds applied here, and the test for
  invoking the weather exception, are the ones stated in the charter party for this
  voyage.</p>
  <p>This notice is advisory negotiation support, not a legal opinion, an arbitration
  award, or a binding determination, and it does not constitute legal advice. Any figure
  stated here should be reviewed against the underlying charter party and source documents
  before it is relied upon or exchanged with a counterparty.</p>
</div>

</div>
</body>
</html>
"""

_TEMPLATE = _ENV.from_string(_TEMPLATE_SOURCE)


def render_letter(data: dict) -> str:
    """Render an HTML settlement letter from a frontend-shaped voyage dict."""
    return _TEMPLATE.render(
        issue_date=date.today().isoformat(),
        **data,
    )
