"""Jinja2 HTML settlement letter for a reconciled voyage."""

from __future__ import annotations

from datetime import date
from jinja2 import Template

_TEMPLATE = Template(
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Demurrage Reconciliation Notice – {{ voyage_id }}</title>
<style>
  body { margin: 0; padding: 0; }
  .letter-container { font-family: Georgia, serif; max-width: 1200px; margin: 40px auto; color: #1a1a1a; }
  .letter-container h1 { font-size: 1.4rem; text-transform: uppercase; letter-spacing: .08em; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; }
  .letter-container h2 { font-size: 1rem; text-transform: uppercase; letter-spacing: .06em; margin-top: 2rem; }
  .letter-container table { width: 100%; border-collapse: collapse; margin-top: .5rem; }
  .letter-container th { text-align: left; font-size: .8rem; text-transform: uppercase; color: #555; border-bottom: 1px solid #ccc; padding: 4px 8px; }
  .letter-container td { padding: 6px 8px; vertical-align: top; }
  .letter-container tr:nth-child(even) td { background: #f9f9f9; }
  .letter-container .verdict-owner { color: #1a5276; font-weight: bold; }
  .letter-container .verdict-charterer { color: #78281f; font-weight: bold; }
  .letter-container .totals { margin-top: 2rem; border-top: 2px solid #1a1a1a; padding-top: 1rem; }
  .letter-container .totals table td:first-child { font-weight: bold; width: 40%; }
  .letter-container .reconciled { font-size: 1.3rem; font-weight: bold; }
  .letter-container .footer { margin-top: 3rem; font-size: .8rem; color: #777; border-top: 1px solid #ccc; padding-top: .5rem; }
</style>
</head>
<body>
<div class="letter-container">

<h1>Demurrage Reconciliation Notice</h1>

<table>
  <tr><th>Voyage ID</th><td>{{ voyage_id }}</td></tr>
  <tr><th>Vessel</th><td>{{ charterparty.vessel_name }}</td></tr>
  <tr><th>Laytime allowed</th><td>{{ charterparty.laytime_allowed_hours }} hours</td></tr>
  <tr><th>Demurrage rate</th><td>${{ "{:,.0f}".format(charterparty.demurrage_rate_per_day_usd) }}/day</td></tr>
  <tr><th>Date of issue</th><td>{{ issue_date }}</td></tr>
</table>

<h2>Party Positions</h2>
<table>
  <tr>
    <th>Party</th>
    <th>Claimed Amount</th>
  </tr>
  <tr>
    <td>Owner</td>
    <td>${{ "{:,.0f}".format(owner_calculation.total_usd) }}</td>
  </tr>
  <tr>
    <td>Charterer</td>
    <td>${{ "{:,.0f}".format(charterer_calculation.total_usd) }}</td>
  </tr>
</table>

<h2>Day-by-Day Adjudication</h2>
<table>
  <tr>
    <th>Date</th>
    <th>Owner Position</th>
    <th>Charterer Position</th>
    <th>Verdict</th>
    <th>Credited (USD)</th>
  </tr>
  {% for v in day_verdicts %}
  <tr>
    <td>{{ v.date }}</td>
    <td>{{ v.owner_position }}</td>
    <td>{{ v.charterer_position }}</td>
    <td class="verdict-{{ v.verdict }}">{{ v.winner_label }}</td>
    <td>${{ "{:,.0f}".format(v.dollars_credited_usd) }}</td>
  </tr>
  {% endfor %}
</table>

{% if day_verdicts %}
<p><em>Justification (final disputed day): {{ day_verdicts[-1].justification }}</em></p>
{% endif %}

<div class="totals">
  <h2>Reconciled Settlement</h2>
  <table>
    <tr><td>Charterer base liability</td><td>${{ "{:,.0f}".format(charterer_calculation.total_usd) }}</td></tr>
    <tr><td>Owner-win items</td><td>${{ "{:,.0f}".format(reconciled_total_usd - charterer_calculation.total_usd) }}</td></tr>
    <tr><td class="reconciled">Reconciled Total</td><td class="reconciled">${{ "{:,.0f}".format(reconciled_total_usd) }}</td></tr>
  </table>
  <p>{{ math_breakdown }}</p>
</div>

<div class="footer">
  Generated by Keel · BIMCO Laytime Definitions 2013 · This notice is for informational purposes only and does not constitute legal advice.
</div>

</div>
</body>
</html>
"""
)


def render_letter(data: dict) -> str:
    """Render an HTML settlement letter from a frontend-shaped voyage dict."""
    return _TEMPLATE.render(
        issue_date=date.today().isoformat(),
        **data,
    )
